resolver: lts-20.24

packages:
- .
# - ../poseidon-hs

extra-deps:
  - git: https://github.com/poseidon-framework/poseidon-hs
    commit: eb7090eb17af7b25a5cb7c7cf1ad836794ae8e2f
  - table-layout-0.9.1.0
  - data-default-instances-base-0.1.0.1
  - sequence-formats-1.7.0
  - pipes-ordered-zip-1.2.1
  - co-log-0.5.0.0
  - ansi-terminal-0.10.3
  - parsec3-numbers-0.1.0
  - chronos-1.1.5
  - typerep-map-0.5.0.0
allow-newer: true