resolver: lts-17.1

packages:
- .

extra-deps:
  - git: https://github.com/poseidon-framework/poseidon-hs
    commit: 01801996c2d62ef27381887b41fa4dc606152444
  - table-layout-0.9.1.0
  - data-default-instances-base-0.1.0.1
  - sequence-formats-1.6.1
  - yaml-pretty-extras-0.0.2.2
  - pipes-ordered-zip-1.2.1
