resolver: lts-21.17

packages:
- .
# - ../poseidon-hs

extra-deps:
  - git: https://github.com/poseidon-framework/poseidon-hs
    commit: c4460ec52f64a47ff0a292a26828fa507802c9a5
  - table-layout-0.9.1.0
  - data-default-instances-base-0.1.0.1
  - sequence-formats-1.7.0
  - pipes-ordered-zip-1.2.1
  - co-log-0.6.0.2
  - ansi-terminal-0.10.3
  - parsec3-numbers-0.1.0
  - chronos-1.1.5
allow-newer: true