resolver: lts-17.1

packages:
- .
# - ../poseidon-hs

extra-deps:
  - git: https://github.com/poseidon-framework/poseidon-hs
    commit: 527600d5248dc70fad32d1c8981d98bb8cc1b4a8
  - table-layout-0.9.1.0
  - data-default-instances-base-0.1.0.1
  - sequence-formats-1.6.1
  - yaml-pretty-extras-0.0.2.2
  - pipes-ordered-zip-1.2.1
