name: Release
on:
  release:
    types: [created]

jobs:
  build-on-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Build Docker image
      run: docker build -t linux -f Dockerfile.linux .
    - name: Create container
      run: docker create --name linuxcontainer linux
    - name: Copy executable
      run: docker cp linuxcontainer:/root/.local/bin/xerxes xerxes-linux
    - name: update-release
      run: bash .github/workflows/upload-github-release-asset.sh github_api_token=${{ secrets.GITHUB_TOKEN }} owner=poseidon-framework repo=poseidon-analysis-hs tag=$(basename $GITHUB_REF) filename=xerxes-linux
  build-on-mac:
    runs-on: macos-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Setup Haskell
      uses: haskell/actions/setup@v1
      with:
        enable-stack: true
    - name: Build
      run: stack install
    - name: Update-release
      run: |
        cp ~/.local/bin/xerxes xerxes-macOS
        bash .github/workflows/upload-github-release-asset.sh github_api_token=${{ secrets.GITHUB_TOKEN }} owner=poseidon-framework repo=poseidon-analysis-hs tag=$(basename $GITHUB_REF) filename=xerxes-macOS
